def bpm2tempo(bpm: int) -> int: ...

class BaseMessage: ...

class Message(BaseMessage):
    def __init__(self, type: str, **args): ...

class MetaMessage(BaseMessage):
    def __init__(self, type: str, **args): ...

class MidiFile:
    tracks: list[MidiTrack]

    def save(self, filename: str): ...

class MidiTrack:
    def append(self, message: BaseMessage) -> None: ...
