import io
from typing import Any

class Object:
    reference: bytes

class Array(Object):
    def __init__(self, values: list[Any]) -> None: ...

class Dictionary(Object):
    def __init__(self, values: dict[str, Any]) -> None: ...

class String(Object):
    def __init__(self, string: bytes | str) -> None: ...

class Stream(Object):
    def begin_text(self) -> None: ...
    def curve_to(
        self, x1: float, y1: float, x2: float, y2: float, x3: float, y3: float
    ) -> None: ...
    def end_text(self) -> None: ...
    def fill_and_stroke(self, even_odd: bool = False) -> None: ...
    def line_to(self, x: float, y: float) -> None: ...
    def move_text_to(self, x: float, y: float) -> None: ...
    def move_to(self, x: float, y: float) -> None: ...
    def pop_state(self) -> None: ...
    def push_state(self) -> None: ...
    def set_color_rgb(
        self, r: float, g: float, b: float, stroke: bool = False
    ) -> None: ...
    def set_font_size(self, font: str, size: float) -> None: ...
    def set_line_width(self, width: float) -> None: ...
    def set_matrix(
        self, a: float, b: float, c: float, d: float, e: float, f: float
    ) -> None: ...
    def show_text(self, text: String) -> None: ...
    def stroke(self) -> None: ...

class PDF:
    pages: Dictionary

    def add_object(self, object_: Object) -> None: ...
    def add_page(self, page: Dictionary) -> None: ...
    def write(self, output: io.BufferedIOBase) -> None: ...
